language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'reactive-coffee' ]; then cd .. && eval "mv $currentfolder reactive-coffee" && cd reactive-coffee; fi

